name: BUILD API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tasuku-api

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose

  publish-api:
   runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tasuku-api
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "rusty-app-001" #Must be unique in Heroku
          heroku_email: "lnimong@gmail.com"

